require("ken.plugins-setup")
require("ken.core.options")
require("ken.core.keymaps")
require("ken.core.colorscheme")
require("ken.plugins.comment")
require("ken.plugins.nvim-tree")
require("ken.plugins.lualine")
require("ken.plugins.telescope")
